Can we catch a MyException?
<class 'example.MyException'> this error should go to a custom type

Can we translate to standard Python exceptions?
<type 'exceptions.RuntimeError'> this error should go to a standard Python exception

Can we handle unknown exceptions?
<type 'exceptions.RuntimeError'> Caught an unknown exception!

Can we delegate to another handler by rethrowing?
<class 'example.MyException'> this error is rethrown

Can we fall-through to the default handler?
<type 'exceptions.RuntimeError'> this error should fall through to the standard handler

Can we catch a MyBaseException?
caught MyBaseException
<class 'example.MyBaseException'> base

Can we catch a MyDerivedException1?
caught MyDerivedException1 derived 1
<class 'example.MyDerivedException1'> derived 1

Can we catch a MyDerivedException2 through MyBaseException?
caught MyBaseException
<class 'example.MyBaseException'> derived 2

